apps/account/urls.py
from django.contrib.auth import views as auth_views
from . import views
from django.urls import path


app_name = 'account'
urlpatterns = [
    path('registration/', views.UserCreateView.as_view(), name='registration'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from apps.api.urls import router
from django.views.generic import TemplateView


admin.site.site_title = 'nutfes-shift-app'
admin.site.site_header = 'NUTFES SHIFT APP'


urlpatterns = [
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('admin/', admin.site.urls),
    path('account/', include('apps.account.urls')),
    path('api/', include(router.urls)),
    path('shift/', include('apps.shift.urls')),
    path('timetable/', include('apps.timetable.urls')),
    path('option/', include('apps.option.urls')),
    path('notification/', include('apps.notification.urls')),
    path('contact/', include('apps.contact.urls')),
    path('markdownx/', include('markdownx.urls')),
]

urlpatterns += static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT
)

templates/base.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>{% block title %}技大祭シフトアプリ{% endblock %}</title>

    {% load static %}
    <!--bootstrap-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">

    <style>
        .body {
            margin: 50px 100px;
        }
        {% block style %}{% endblock %}
    </style>
</head>

<body class="body">
    {% block content %}{% endblock %}

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>
    {% block javascript %}{% endblock %}
</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block content %}
    <h1>技大祭シフトアプリ</h1>
    <hr>
    <br>
    {% if user.is_authenticated %}
        <p>ログインしています．</p>
        <p>ユーザ: {{ user.name }}</p>
        <p>▶︎ {% if user.is_staff %}<a href="{% url 'admin:index' %}">管理画面</a>{% endif %}</p>
        <p>▶︎ <a href="{% url 'account:logout' %}">ログアウト</a></p>
    {% else %}
        <p>ログインしていません．</p>
        <p>▶︎ <a href="{% url 'admin:index' %}">ログイン</a></p>
        <p>▶︎ <a href="{% url 'account:registration' %}">ユーザ登録</a></p>
    {% endif %}
{% endblock %}